### ISSUE TITLE
cant import vib ribbon models

### ISSUE THREAD

**Issue by Tubnubz** [Murugo/Misc-Game-Research#4]
i followed the read me file just as said but it shows up as an error and does not import, also took a look at the script and it showed up as this (highlighted)
i have used blender 2.80 to 3.2 but cant get it to work
![help pls](https://user-images.githubusercontent.com/114278139/192082524-7cc07fe8-5af1-4fca-a2da-6c2cbf5185ad.png)
![help](https://user-images.githubusercontent.com/114278139/192082526-e75c874a-af8d-4d90-9899-d53b272ea69f.png)
all that i am trying to do is download some vib ribbon model for a project

**Comment by ghost** [comment]
You have to go on the blender addons folder, and go on **io_vib_ribbon**, delete the readutil file and put the readutil folder that is avaliable here: https://cdn.discordapp.com/attachments/939246273423355908/1001254517070888980/readutil.zip
restart blender and it should work

**Comment by Tubnubz** [comment]
didnt get it at first but now its working as intended. thx
