### ISSUE TITLE
why are vib ribbon models all condensed together

### ISSUE THREAD

**Issue by Tubnubz** [Murugo/Misc-Game-Research#6]
![model_problems](https://user-images.githubusercontent.com/114278139/192414399-2871bc21-fba9-4878-ae22-39571db9cf9a.png)
any model I import seems to condense to the center of my work area and I don't know how to fix it
side note: i have tried to add an animation file to see if it sorts it out and not sure if it worked or if i tried using the wrong animation for the wrong model, i will continue to tinker with it until further notice

**Comment by Tubnubz** [comment]
something new happened

https://user-images.githubusercontent.com/114278139/192416300-839547a0-88d2-43eb-b280-888c12a0c1a5.mp4
i dont know if it is progress or not but it also seems to be missing the wire frames

**Comment by Tubnubz** [comment]
small but another update: from what I have noticed is that the models will be scrunched up until you get the animation file added to the model which will sort of set things straight. only problem (at least for me) is that the wire frames from all of the models are missing except for the 2-3 random triangles that appear

**Comment by ghost** [comment]
just click here
![Captura de tela 2022-09-28 040138](https://user-images.githubusercontent.com/86070645/192663992-a7eabcf3-a684-48c2-90ad-5a9a1a21c675.png)

**Comment by Tubnubz** [comment]
dude i was just about to say the same thing, just found that out
